### ISSUE TITLE
Settings giving a KeyError

### ISSUE THREAD

**Issue by andradei** [brpaz/ulauncher-vscode-projects#16]
Having my settings like this:

![image](https://user-images.githubusercontent.com/2653546/115136180-548b4680-9fdb-11eb-94bd-bcc41e39de04.png)

I'm getting this error:

Message: 'com.github.brpaz.ulauncher-vscode-projects'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-vscode-projects'

```

I tried escaping the spaces on the paths like so
`~/.config/Code\ -\ OSS/` but no luck.

**Comment by brpaz** [comment]
You probably are missing a Python extension. Make sure you do on your terminal:

```
pip install --user memoization==0.4.0
```

Also see: https://ulauncher-extension-doesnt-install-and-now.netlify.app/
