### ISSUE TITLE
can't add addon 

### ISSUE THREAD

**Issue by ghost** [brpaz/ulauncher-vscode-projects#19]
Hello i would like to install the addon but i get this error. 

`Message: 'com.github.brpaz.ulauncher-vscode-projects'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-vscode-projects'

````

**Comment by brpaz** [comment]
You probably are missing a Python extension. Make sure you do on your terminal:

```
pip install --user memoization==0.4.0
```

Also see: https://ulauncher-extension-doesnt-install-and-now.netlify.app/
