### ISSUE TITLE
stuck on Loading

### ISSUE THREAD

**Issue by jsavalle** [brpaz/ulauncher-vscode-projects#2]
![screenshot](https://user-images.githubusercontent.com/5922799/52247963-5f6eca80-28ec-11e9-8575-bff657762ed1.png)

~/.config/Code/User/projects.json is there and working - permissions are correct...
I don't see why it is not working.

**Comment by ddoice** [comment]
Same here:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/xxxxxx/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-vscode-projects/main.py", line 57, in on_event
    description=project['fullPath'],
KeyError: 'fullPath'
`
