### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by jsardev** [brpaz/ulauncher-vscode-projects#5]
Unfortunately the extension is still stuck on loading :cry: 

```
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]: Traceback (most recent call last):
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:   File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Client.py", line 52, in on_message
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:     self.extension.trigger_event(event)
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:   File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:     action = listener.on_event(event, self)
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:   File "/home/jsarnowski/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-vscode-projects/main.py", line 57, in on_event
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]:     description=project['rootPath'],
May 16 18:45:35 Kuba-PC ulauncher.desktop[32134]: KeyError: 'rootPath'
```

**Comment by brpaz** [comment]
This is related to a change of the Project Manager extension. It should be fixed now. Make sure you refresh your projects inside VS Code. (Open Command Pallete -> Project Manager: Refresh Projects)
